name: Block merging main into release branches

on:
  pull_request:
    branches:
      - "all/release/*"
      - tc/task/DEVOPSDSC-549-prevent-merging-main-into-release-branches # temporary to test if main can be merged into this feature branch

jobs:
  block-merging-main-into-release-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Block merging if Fail if source branch is main
        if: github.head_ref == 'main'
        run: |
          echo "‚ùå Pull requests from 'main' into all/release/* are not allowed."
          exit 1
